GPLv3라이선스를 위반을 해결하기 위한 수정입니다
Flug-in-Fabrik/Pmarket pull request #2
Opened 2020-02-06 14:24 UTC by PresentKim

#1 에 따라 해당 플러그인은 GPLv3를 적용해야하므로 라이센스 파일을 수정했습니다

2020-02-06 14:41 UTC, nnnlog requested changes
코드 내부에 GPLv3 라이선스에 관한 내용을 주석으로 삽입하는게 맞지 않나요?

2020-02-07 09:03 UTC, Securti commented
라이센스 변경하였습니다..!

2020-02-07 09:07 UTC, PresentKim commented
Merge를 하시는게 아니라 그냥 수정 내용만 가져다 사용하셨네요..

2020-02-10 14:06 UTC, PresentKim commented
그냥 Close 하고 도주하겠습니다!

2020-02-10 14:06 UTC, closed without merging